### ISSUE TITLE
Playtimes stuck at 0s for all offline players.

### ISSUE THREAD

**Issue by Ignerium** [CodedRed-Spigot/PlayTimes#10]
How would I make it so offline player's times get displayed also?

**Comment by Produktecheck** [comment]
I have the same problem

**Comment by Mcklp** [comment]
i have the same problem

**Comment by Zoltus** [comment]
> How would I make it so offline player's times get displayed also?
> I have the same problem
> i have the same problem
i got forket version for 1.19 check pullrequest or my repositys and releases
