### ISSUE TITLE
Offline players not working since 1.18

### ISSUE THREAD

**Issue by Log1x** [CodedRed-Spigot/PlayTimes#13]
![Screenshot](https://i.imgur.com/wyPey84.png)

No errors.

**Comment by CodedRedGIT** [comment]
Sorry for the late response, 
Is your server in online or offline mode?

**Comment by Log1x** [comment]
Offline mode (BungeeCord)

There appears to be someone else having this issue as well in the [Discussions on spigot](https://www.spigotmc.org/threads/playtimes-check-players-playtime-server-uptime.329363/page-12#post-4325783).

**Comment by CodedRedGIT** [comment]
Okay thanks for reporting, I'll check it out and post an update soon!
