### ISSUE TITLE
Formats in Placeholder issue

### ISSUE THREAD

**Issue by Silvobi** [CodedRed-Spigot/PlayTimes#14]
So in config file I set everything like that:
![image](https://user-images.githubusercontent.com/54009037/153425727-a8381568-4a07-41b6-9a36-2ebd30a5c2d6.png)
However when I wanted to make a Placeholder in HolographicsDisplay plugin it looks like that
![image](https://user-images.githubusercontent.com/54009037/153425818-69f253ce-feca-494b-be63-a4f129e6cb02.png)
The proplem is formats seems like does not work for placeholders I dunno why.

config.yml → https://pastebin.com/ZFvSmZTb

**Comment by CodedRedGIT** [comment]
Have you tried reloading both plugins, you may also have to restart the server.
