### ISSUE TITLE
Don’t count afk players

### ISSUE THREAD

**Issue by dh2-io** [CodedRed-Spigot/PlayTimes#17]
It would be cool and also helpful if there would be an option to ignore afk players.

**Comment by steveminecraft2** [comment]
> It would be cool and also helpful if there would be an option to ignore afk players.

this would be very useful, hope it will be added as soon as possible

**Comment by CodedRedGIT** [comment]
https://github.com/CodedRed-Spigot/PlayTimes/issues/11
