### ISSUE TITLE
%PlayTimes_joindate% issue

### ISSUE THREAD

**Issue by WarnDa** [CodedRed-Spigot/PlayTimes#23]
When a user first join the server, unless he disconnect, it will tell he never joined the server : 
![image](https://user-images.githubusercontent.com/31826333/204010427-cf916680-6040-46c8-9c20-861d57b44452.png)

but /seen show him online : 
![image](https://user-images.githubusercontent.com/31826333/204010491-2cda85b2-cd27-4c22-a606-b62e1d2453fc.png)
(it's french but it means he is online since 39s)

**Comment by CodedRedGIT** [comment]
Thank you for reporting, unfortunately this is how the joindate placeholder was originally coded. I will add this to my to-do list.

**Comment by WarnDa** [comment]
> Thank you for reporting, unfortunately this is how the joindate placeholder was originally coded. I will add this to my to-do list.

Hello,
Any news after this time ?
