### ISSUE TITLE
PlayTimes showing wrong top players

### ISSUE THREAD

**Issue by Sniped** [CodedRed-Spigot/PlayTimes#25]
PlayTimes is not showing the right top players for playtime on the leaderboard. I am using the latest version of the plugin, 1.4.7. 

On a 1.19.3 offline server running Pufferfish with build `git-Pufferfish-52`, connected through a Velocity proxy, I have a play time of 3 days (shown below)

![](https://i.imgur.com/DR2kBmH.png)

However, when I look at the leaderboard, the top player is one with 9 hours of playtime (shown below)

![](https://i.imgur.com/yZUXaTl.png)

I am unsure how to resolve this issue. Is it an issue with the plugin or an issue with my server? I can provide additional information about the server if needed.

**Comment by CodedRedGIT** [comment]
Thanks for reporting, I am slowly updating all my plugins. I will look into this asap!
