### ISSUE TITLE
[Feature Request] Ability to exempt certain players from leaderboards

### ISSUE THREAD

**Issue by InAgony** [CodedRed-Spigot/PlayTimes#26]
A command like `/playtime exempt {player}` would be helpful for staff who AFK a lot, a needed feature for our server at least :D

**Comment by CodedRedGIT** [comment]
Thanks for the suggestion! Currently you can use the 'block' command to hide players from the playtime top leaderboard.
Usage:

`/playtime block <player> - blocks player from being on the leaderboards`
