### ISSUE TITLE
HolographicDisplays 

### ISSUE THREAD

**Issue by NesoiDesigner** [CodedRed-Spigot/PlayTimes#27]
![image](https://user-images.githubusercontent.com/121246392/215823617-92b98a1a-5fe5-46b0-af32-2dfd2ceb7f32.png)

how can i show this in hologram? 
%playtimes_toptime1%
%playtimes_topname1%

**Comment by CodedRedGIT** [comment]
Do you have [PAPI ](https://www.spigotmc.org/resources/placeholderapi.6245/) installed? 
If so could you run, `/papi list` to see if "PlayTimes" is in there?

PlayTimes will automatically activate its PAPI placeholders on server startup. If PlayTimes is in the PAPI list then you may need another plugin to communicate with HolographicDisplays to handle the PAPI placeholders. Such as https://www.spigotmc.org/resources/holographicextension.18461/

If PlayTimes is not on the PAPI list, try restarting your server. If the problem consists I'll run tests on my side.
