### ISSUE TITLE
Top Playtime getting reset randomly on 1.19.3

### ISSUE THREAD

**Issue by InAgony** [CodedRed-Spigot/PlayTimes#28]
Randomly /toppt and any leaderboards made using the placeholders reset the top playtime players, starting from zero and counting up again. The actual playtime isn't affected.

**Comment by CodedRedGIT** [comment]
Did you modify the leaderboard folder manually at all?

**Comment by InAgony** [comment]
No, the folder has not been touched.

**Comment by CodedRedGIT** [comment]
Okay, I apologize for this issue. I'm currently working on updates to the plugin and will look into the leaderboard. Thanks for reporting.

**Comment by CodedRedGIT** [comment]
https://github.com/CodedRed-Spigot/PlayTimes/releases/tag/v1.5
