### ISSUE TITLE
Legacy plugin Playtimes v1.4.5 does not specify an api-version

### ISSUE THREAD

**Issue by Proomp** [CodedRed-Spigot/PlayTimes#3]
Sever version: Airplane 1.16.5
[11:16:21] [Server thread/WARN]: Legacy plugin Playtimes v1.4.5 does not specify an api-version.

**Comment by CodedRedGIT** [comment]
Thanks for reporting. This isn't a bug. PlayTimes doesn't specify its API because past versions were experiencing issues when it was specified. I can look into this again but for now, I will be closing this issue. Thanks!

**Comment by NotAlexNoyle** [comment]
> Thanks for reporting. This isn't a bug. PlayTimes doesn't specify its API because past versions were experiencing issues when it was specified. I can look into this again but for now, I will be closing this issue. Thanks!

Have you done any further investigation about this? If not, could you? PlayTimes is one of only two "legacy" plugins on my server and I'd like to bring it in line with the rest. Thanks.

**Comment by Gamemap** [comment]
@CodedRedGIT Any news on this?

**Comment by NotAlexNoyle** [comment]
I've been using a fork with the API version specified for months now with no issues.

**Comment by Gamemap** [comment]
@NotAlexNoyle  Would it be possible for you to upload the .jar so I could use it too?

**Comment by NotAlexNoyle** [comment]
> @NotAlexNoyle Would it be possible for you to upload the .jar so I could use it too?

https://github.com/NotAlexNoyle/PlayTimes/releases/tag/release
