### ISSUE TITLE
 Player playtime not visible for offline players.

### ISSUE THREAD

**Issue by Produktecheck** [CodedRed-Spigot/PlayTimes#31]
Hello, I have the Playtime plugin. But since I updated to server version 1.20, I only see the playtimes of the players who are currently online.

**Comment by CodedRedGIT** [comment]
Thanks for reporting, will update to support 1.20.

**Comment by Produktecheck** [comment]
That sounds great. When do you think you'll have it done by?

**Comment by CodedRedGIT** [comment]
> That sounds great. When do you think you'll have it done by?

It will be the first thing on my to-do list when I return from Vacation—unfortunately caught me at a busy time. I will be back Sunday the 9th. I will have the plugin updated by the night of the 11th.

**Comment by CodedRedGIT** [comment]
> Hello, I have the Playtime plugin. But since I updated to server version 1.20, I only see the playtimes of the players who are currently online.

What version of Minecraft did you update from? Like 1.19 -> 1.20 or was it an older version?

**Comment by Produktecheck** [comment]
1.19 -> 1.20

**Comment by CodedRedGIT** [comment]
Will be posting soon on spigotmc.org, pre-release download can be found here: https://github.com/CodedRed-Spigot/PlayTimes/releases/tag/v1.5

If you have any questions or run into any problems please feel free to open another ticket. Thank you.
