### ISSUE TITLE
Toppt invisible players

### ISSUE THREAD

**Issue by skyman478** [CodedRed-Spigot/PlayTimes#35]
The /toppt command returns a list with invisible players, but with visible play times
plugin version: 1.5.2

![image](https://github.com/CodedRed-Spigot/PlayTimes/assets/59271049/9dc09041-823e-43b0-93fc-fe2fa97b1666)

**Comment by CodedRedGIT** [comment]
Sorry I missed this report, please repost your report with the following information and I will get back to you asap!
- Server Version
- PlayTimes Version
- Offline/Online Server
You can run the command /version in-game and then send a screenshot of that to make it easier for you.
