### ISSUE TITLE
Some players doesn't show up in leaderboard

### ISSUE THREAD

**Issue by shaqupl** [CodedRed-Spigot/PlayTimes#38]
![image](https://github.com/CodedRed-Spigot/PlayTimes/assets/68109218/0b3abb0e-a9a6-4e03-9384-7ef051fb6e9e)
Here is leaderboard on my server. My playtime is on the bottom 1d13h so I should be first. I'm not the only one who doesn't show up in leaderboard, nearly half of my server is not in the leaderboard

**Comment by shaqupl** [comment]
Also, players that are currently offline displays as 0s

**Comment by CodedRedGIT** [comment]
Thanks for reporting.
Can you please provide the following information so I can investigate this issue further?

- Server Version

- Is your server online or offline?

- Did you recently update your server version? If so what was the old version

- What version of PlayTimes are you using?
