### ISSUE TITLE
Only online players are showing on the leaderboard

### ISSUE THREAD

**Issue by Digggon** [CodedRed-Spigot/PlayTimes#4]
anyone who is offline is shown having a playtime as "0s."

**Comment by ShavedBIrd** [comment]
Getting this same issue, however it does show the playtime of offline players if they haven’t joined since an older version of playtimes was being used in my server

**Comment by OyotOnyenwe** [comment]
also getting this after updating to PlayTimes 1.4.5 and Paper 1.18

**Comment by CodedRedGIT** [comment]
Thanks for reporting, this seemed to be a 1.18 issue. In the latest update, this is fixed. If you are reporting this issue for an older version please open another ticket. Thanks!
