### ISSUE TITLE
[Features Request] Add a Database features ?

### ISSUE THREAD

**Issue by OverStyleFR** [CodedRed-Spigot/PlayTimes#40]
Hi

I just asking if you can add a features to connecte this plugins in to a database (MySQL)

**Comment by CodedRedGIT** [comment]
Thanks for the request! This is on the todo list!

**Comment by OverStyleFR** [comment]
> Thanks for the request! This is on the todo list!

Thanks ^^

**Comment by CodedRedGIT** [comment]
> Hey there, I noticed you are already adding some Database features. Are you interested in some help to keep the implementation clean and more maintainable?

Feel free to make a pull request! I cannot guarantee I will accept it but I am open to suggestions. The database stuff is very alpha, only worked on it for a day. Thank you very much!

**Comment by CodedRedGIT** [comment]
Added
