### ISSUE TITLE
afk player

### ISSUE THREAD

**Issue by SpadaccinoNero7** [CodedRed-Spigot/PlayTimes#42]
[QUESTION/FEATURE REQUEST]
It's possible to NOT count playtime for afk players?

**Comment by CodedRedGIT** [comment]
> [QUESTION/FEATURE REQUEST] It's possible to NOT count playtime for afk players?

Thanks for the suggestions! This is the next feature that is being added after database support. 

The database update should be coming out this week.

**Comment by CodedRedGIT** [comment]
AFK tracker as been added.
