### ISSUE TITLE
Adding Permissions so non OP Player can check the playtimes

### ISSUE THREAD

**Issue by K1L1AN** [CodedRed-Spigot/PlayTimes#43]
It is statet that it is possible to add permissions so non OP- Player can check their playtime or the leaderboard for example.

In the Wiki it states:
_pt.use - Lets you use /playtime.
pt.others - Lets you check others playtime.
pt.uptime - Lets you check server uptime.
pt.reload - Lets you reload & more.
pt.block - Lets you block players from being on the leaderboard
pt.top - Lets you use /toppt
pt.block-cooldown - No cooldown for /toppt_

How excactly does one add permissions in the config? What comes after "pt.top" for example? I have tried "default" or "true" but nothing worked.
Thank you in advance!

**Comment by NotAlexNoyle** [comment]
> It is statet that it is possible to add permissions so non OP- Player can check their playtime or the leaderboard for example.
> 
> In the Wiki it states: _pt.use - Lets you use /playtime. pt.others - Lets you check others playtime. pt.uptime - Lets you check server uptime. pt.reload - Lets you reload & more. pt.block - Lets you block players from being on the leaderboard pt.top - Lets you use /toppt pt.block-cooldown - No cooldown for /toppt_
> 
> How excactly does one add permissions in the config? What comes after "pt.top" for example? I have tried "default" or "true" but nothing worked. Thank you in advance!

You need LuckPerms

**Comment by K1L1AN** [comment]
Thanks!
