### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by HoweCraft** [CodedRed-Spigot/PlayTimes#44]
Could not load 'plugins\PlayTimes-1.6 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/codedred/playtimes/PlayTimes has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by CodedRedGIT** [comment]
Thank you for reporting this! I will fix this ASAP! For now try using an older version: https://www.spigotmc.org/resources/playtimes-track-player-playtime.58858/history

**Comment by CodedRedGIT** [comment]
https://www.spigotmc.org/resources/playtimes-track-player-playtime.58858/update?update=538247

Should be fixed in the latest version. Please make another ticket if you need further help!
