### ISSUE TITLE
Request & Suggestion (new placeholder etc.)

### ISSUE THREAD

**Issue by emirhan03** [CodedRed-Spigot/PlayTimes#46]
- A raw placeholder containing a numeric value such as %playtime_minutes% should be added to the plugin for annual, monthly, weekly, daily sorting and compatibility with ajleaderboards.

- If possible, the sql storage option should be added and we should be able to migrate from yaml storage.

**Comment by CodedRedGIT** [comment]
>A raw placeholder containing a numeric value such as %playtime_minutes% should be added to the plugin for annual, monthly, weekly, daily sorting and compatibility with ajleaderboards.
This is a planned future update. No eta, I need to plan a good strategy for handling this.

>If possible, the sql storage option should be added and we should be able to migrate from yaml storage.
PlayTimes doesn't use much info from its own yaml files. All of the actually playtime values are stored in the world folder. I could add a feature to migrate the leaderboard info into SQL storage.  Thanks for the suggestions!

**Comment by CodedRedGIT** [comment]
Closing this ticket because this ticket has already been made:
https://github.com/CodedRed-Spigot/PlayTimes/issues/16

Thank you for the suggestions!
