### ISSUE TITLE
Formated placeholders

### ISSUE THREAD

**Issue by vxkShelby** [CodedRed-Spigot/PlayTimes#47]
can you please add formated placeholders ? for example "10D 19h" or something like that

**Comment by CodedRedGIT** [comment]
> can you please add formated placeholders ? for example "10D 19h" or something like that

I'm not sure what you mean by this. 
The time placeholders are formatted and the format can be changed in the config.yml
`  name:
    second: "s"
    minute: "min "
    hour: "hr "
    day: "day "
    seconds: "s"
    minutes: "mins "
    hours: "hrs "
    days: "days "`

**Comment by CodedRedGIT** [comment]
Need more info.
