### ISSUE TITLE
no nicks in the top 

### ISSUE THREAD

**Issue by TymekSL** [CodedRed-Spigot/PlayTimes#50]
I dont see nicks in the top playtime wtf, 1.6.1 version. I still waiting for fix luckperms prefixes for hex but here didnt use this
FIX!!!!!!!

**Comment by TymekSL** [comment]
https://prnt.sc/1R7IxqY-f8Rv

**Comment by TymekSL** [comment]
Lmao

**Comment by CodedRedGIT** [comment]
Thanks for reporting, this is an interesting bug. Will be fixed in next update. What nickname plugin are you using?

**Comment by CodedRedGIT** [comment]
Related: https://github.com/CodedRed-Spigot/PlayTimes/issues/51
