### ISSUE TITLE
I'm linking PlayTimes to Skript, but I need help

### ISSUE THREAD

**Issue by ef1m03** [CodedRed-Spigot/PlayTimes#53]
### my code in Skript

 on block place:
   set {_timePlayed} to getPlayTime()
    if {_timePlayed} < 10:
        set {_spawn} to location of world's spawn
        if distance between event-location and {_spawn} < 256:
            cancel event
            send "&cYou cannot destroy blocks within the spawn protection radius for up to 10 hours of game time!" to the player

on block break:
    set {_timePlayed} to getPlayTime()
    if {_timePlayed} < 10:
        set {_spawn} to location of world's spawn
        if distance between event-location and {_spawn} < 256:
            cancel event
            send "&cYou cannot destroy blocks within the spawn protection radius for up to 10 hours of game time!" to the player
            
            
 **ERROR in game:** 
![image](https://github.com/CodedRed-Spigot/PlayTimes/assets/57316954/ade2fe65-8362-4dcf-a669-c9232fd60d1b)

How should I replace my code on lines 4 and 14? **set {_timePlayed} to getPlayTime()**

**Comment by CodedRedGIT** [comment]
PlayTimes is not a script. I can look into adding support for this. Thank you for the report.
