### ISSUE TITLE
playtimes api-version

### ISSUE THREAD

**Issue by MuratAb54** [CodedRed-Spigot/PlayTimes#55]
When you install the playtimes plugin, it gives this warning

**Comment by MuratAb54** [comment]
![image](https://github.com/CodedRed-Spigot/PlayTimes/assets/125699753/024a819b-42ca-4e53-b885-1d5b67ae83b9)

**Comment by CodedRedGIT** [comment]
Thanks for reporting, will fix in next update.

**Comment by CodedRedGIT** [comment]
This is resolved in the newest release coming out tomorrow. 
https://github.com/CodedRed-Spigot/PlayTimes/releases/tag/v1.6.2
