### ISSUE TITLE
Major Lag (TPS Drops to 1.5)

### ISSUE THREAD

**Issue by DarkChromaMC** [CodedRed-Spigot/PlayTimes#57]
**Description:**
We have encountered an issue where the Playtimes plugin intermittently causes severe lag spikes on our Minecraft server. These lag spikes occur randomly several times each week and have a substantial impact on server performance, reducing the Ticks Per Second (TPS) to as low as 1.5.

**Environment:**
- **Plugin Version:** 1.6.1
- **Minecraft Server Version:** 1.20.4
- **Hardware Configuration:** [Include server hardware information if available]

**Reproduction Steps:**
1. Install Playtimes plugin version 1.6.1 on Minecraft server version 1.20.4.
2. Monitor the server performance, specifically TPS, over the course of the week.
3. Observe the occurrence of random lag spikes.

**Expected Behavior:**
The server should operate without significant drops in TPS, maintaining a stable performance irrespective of the usage of the Playtimes plugin.

**Actual Behavior:**
The server experiences dramatic drops in TPS to about 1.5 during random intervals, which appear to be associated with the Playtimes plugin.

**Additional Information:**
- **Spark Profile Link:** [Spark Profile during Lag Spike](https://spark.lucko.me/AJFFAnpNP5)
- **Screenshots:** 
   - ![Lag Spike Evidence](https://github.com/CodedRed-Spigot/PlayTimes/assets/68839442/3437a6ea-1aae-4cd5-8142-7282997d93e7)
   - ![Spark Profile Screenshot](https://github.com/CodedRed-Spigot/PlayTimes/assets/68839442/dc8d2c29-8e8c-44e3-8c13-a23e9aef4291)

**Logs:**
- [latest.log](https://github.com/CodedRed-Spigot/PlayTimes/files/15416196/latest.log)

This report aims to highlight the recurring issue of performance degradation potentially linked to the Playtimes plugin, and we are seeking assistance in diagnosing and resolving this problem to improve server stability.

**Comment by CodedRedGIT** [comment]
Thank you for this thorough report. Everything that was causing the lag spike has been optimized. If you experience this issue again, I will make haste to fix it. I apologize for the inconvenience, but I greatly appreciate your report.

As of version 1.6.2, the files with these issues have been optimized, so I am now closing this ticket.
