### ISSUE TITLE
[SUGGESTION] Linked Playtime

### ISSUE THREAD

**Issue by xOnlyFadi** [CodedRed-Spigot/PlayTimes#67]
# Suggestion Template

---

## Suggestion

**Description:**
- A Linked playtime is to make all server use one playtime for all users if a player played on Server A then it playtime transfers to Server B so that the playtime could be working for the rewards for a player that needs a specific time to rewards for it 

**Benefits:**
- It would improve for players that play many games on servers and their playtime would be linked to all servers without being worrie that their time Is wasted just play one game that has this playtime inside it.

**Comment by CodedRedGIT** [comment]
You can use `%global_playtime%` and `%global_rawtime%`

https://github.com/CodedRed-Spigot/PlayTimes/wiki/Bungee-Support


```
Plugin Use:

%rawtime_serverId% - The total time spent on the server.
%afktime_serverId% - The time spent AFK (Away From Keyboard) on the server.
%playtime_serverId% - The active playtime on the server (rawtime minus afktime, if afk is enabled).
%global_playtime% - The total playtime from all servers.
%global_rawtime% - The total rawtime from all servers.
%global_afktime% - The total afktime from all servers.
```

**Comment by xOnlyFadi** [comment]
will it choose the highest playtime for default global placeholder

**Comment by CodedRedGIT** [comment]
It combines the playtime from all servers and returns the total global time for that player.

**Comment by xOnlyFadi** [comment]
one question some of the plugins uses the stats file of a player and cannot get the global count of the playtime plugin is there a way to make an option it saves the playtime as that?

**Comment by CodedRedGIT** [comment]
Playtimes does not modify the players stats file. If you enable database support it will save the player's playtime in either MySQL or SQLite so that the global placeholder can grab the time from other servers. 

For other plugins to get the global time from Playtimes you would have to use PlaceholdersAPI. Eventually there will be better API for plugins to hook into PlayTimes.

```
For PlaceholderAPI (PAPI) Integration:

%PlayTimes_rawtime_serverId%
%PlayTimes_afktime_serverId%
%PlayTimes_playtime_serverId%
%PlayTimes_global_playtime%
%PlayTimes_global_rawtime%
%PlayTimes_global_afktime%
```

**Comment by xOnlyFadi** [comment]
I understand, thank you for help.
