### ISSUE TITLE
1.18 problem

### ISSUE THREAD

**Issue by Tuurkevg** [CodedRed-Spigot/PlayTimes#7]
problem on 1.18 only see 0S on each player. only the highest number is showing correctly. Could you support 1.18? 
![afbeelding](https://user-images.githubusercontent.com/77327545/145073932-c90e8fa9-d87d-479d-954b-1140e835ef49.png)

**Comment by CodedRedGIT** [comment]
Did you update your server from 1.17 to 1.18 or a previous version?

**Comment by CodedRedGIT** [comment]
Fixed this issue. Posting the update soon!
