### ISSUE TITLE
[enhancement] Leaderboard position placeholder

### ISSUE THREAD

**Issue by bumpyJake** [CodedRed-Spigot/PlayTimes#8]
Add a PlaceholderAPI placeholder to display what position someone is in on the leaderboard. This could be used for chat/tab prefixes.

Example: `%PlayTimes_leaderboard_pos%` would return "2" if second on /toppt

**Comment by CodedRedGIT** [comment]
There is already a way to get the top 10 players' names and timings. The position number can be done by yourself. I can maybe look into adding a another PAPI placeholder for this in the future.
