### ISSUE TITLE
Add placeholders

### ISSUE THREAD

**Issue by Safarival** [CodedRed-Spigot/PlayTimes#9]
Hello,

I find your plugin excellent and thank you for all the hard work you have put into this free plugin. I would like to know if it would be possible for you to make sure to add placeholders on Bungeecord to retrieve playing time, ranking, ..., from one server to another server please?
Example: % PlayTimes_playtime_server_ <servername>%

**Comment by CodedRedGIT** [comment]
I can look into adding some sort of PAPI placeholder for this feature. Eventually, (once I have more free time) I will code a better more fluid system but for now this isn't a bad idea.
